# Generated by Django 4.0.6 on 2023-01-07 14:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0002_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('selling_price', models.FloatField()),
                ('discounted_price', models.FloatField()),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('PF', 'Perfumes'), ('MB', 'Mobiles'), ('FW', 'FaceWash'), ('FC', 'FaceCream'), ('SP', 'Soaps'), ('LP', 'Laptops'), ('TV', 'Tvs'), ('BS', 'BodySprays')], max_length=2)),
                ('product_image', models.ImageField(upload_to='product')),
            ],
        ),
        migrations.RenameModel(
            old_name='Customer',
            new_name='Customers',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
