# Generated by Django 4.0.6 on 2023-01-08 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_products_rename_customer_customers_delete_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('selling_price', models.FloatField()),
                ('discounted_price', models.FloatField()),
                ('description', models.TextField()),
                ('Benfits', models.TextField()),
                ('category', models.CharField(choices=[('PF', 'Perfumes'), ('MB', 'Mobiles'), ('FW', 'FaceWash'), ('FC', 'FaceCream'), ('SP', 'Soaps'), ('LP', 'Laptops'), ('TV', 'Tvs'), ('BS', 'BodySprays')], max_length=2)),
                ('product_image', models.ImageField(upload_to='product')),
            ],
        ),
        migrations.DeleteModel(
            name='Products',
        ),
    ]
